### Using numpy only

In [1]:
import numpy as np

In [45]:
X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)

w = np.array([0.0])

In [25]:
def forward(X, w):
    y = X*w
    return y

In [49]:
def loss_func(y_pred, y):
    return ((y_pred - y)**2).mean()

In [27]:
def gradient_func(X, w, Y):
    # d(loss)/dw = d(1/N*((x*w - y)**2))/dw
    # d(loss)/dw = 2(x*w - y) x/N
    return np.mean(2*X*(X*w - Y))

In [46]:
lr = 0.1
epochs = 15
for i in range(epochs):
    y_pred = forward(X, w)
    loss = loss_func(y_pred, Y)
    dw = gradient_func(X, w, Y)
    
    w -= lr*dw
    
    print(f'epoch {i+1}: weight = {w[0]:.3f}, loss = {loss:.8f}')

print(f'\nPrediction after training f(5) = {forward(5, w)[0]:.3f}\n')

epoch 1: weight = 3.000, loss = 30.00000000
epoch 2: weight = 1.500, loss = 7.50000000
epoch 3: weight = 2.250, loss = 1.87500000
epoch 4: weight = 1.875, loss = 0.46875000
epoch 5: weight = 2.062, loss = 0.11718750
epoch 6: weight = 1.969, loss = 0.02929688
epoch 7: weight = 2.016, loss = 0.00732422
epoch 8: weight = 1.992, loss = 0.00183105
epoch 9: weight = 2.004, loss = 0.00045776
epoch 10: weight = 1.998, loss = 0.00011444
epoch 11: weight = 2.001, loss = 0.00002861
epoch 12: weight = 2.000, loss = 0.00000715
epoch 13: weight = 2.000, loss = 0.00000179
epoch 14: weight = 2.000, loss = 0.00000045
epoch 15: weight = 2.000, loss = 0.00000011

Prediction after training f(5) = 10.000



### with Pytorch

In [40]:
import torch

In [57]:
X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y = torch.tensor([2,4,6,8], dtype=torch.float32)

w = torch.tensor([0.0], requires_grad=True)

In [59]:
def forward(X, w):
    y = X*w 
    return y

In [60]:
def loss_func(y_pred, y):
    return ((y_pred - y)**2).mean()

In [58]:
lr = 0.1
epochs = 100

for i in range(epochs):
    y_pred = forward(X, w)
    loss = loss_func(y_pred, Y)
    loss.backward()
    
    # we dont want this step to be included in computaitonal graph for calculating gradient
    with torch.no_grad():
        w -= lr*w.grad
    
    w.grad.zero_()
    
    if (i%5==0):
        print(f'epoch {i+1}: weight = {w[0]:.3f}, loss = {loss:.8f}')

print(f'\nPrediction after training f(5) = {forward(5, w)[0]:.3f}\n')

epoch 1: weight = 3.000, loss = 30.00000000
epoch 6: weight = 1.969, loss = 0.02929688
epoch 11: weight = 2.001, loss = 0.00002861
epoch 16: weight = 2.000, loss = 0.00000003
epoch 21: weight = 2.000, loss = 0.00000000
epoch 26: weight = 2.000, loss = 0.00000000
epoch 31: weight = 2.000, loss = 0.00000000
epoch 36: weight = 2.000, loss = 0.00000000
epoch 41: weight = 2.000, loss = 0.00000000
epoch 46: weight = 2.000, loss = 0.00000000
epoch 51: weight = 2.000, loss = 0.00000000
epoch 56: weight = 2.000, loss = 0.00000000
epoch 61: weight = 2.000, loss = 0.00000000
epoch 66: weight = 2.000, loss = 0.00000000
epoch 71: weight = 2.000, loss = 0.00000000
epoch 76: weight = 2.000, loss = 0.00000000
epoch 81: weight = 2.000, loss = 0.00000000
epoch 86: weight = 2.000, loss = 0.00000000
epoch 91: weight = 2.000, loss = 0.00000000
epoch 96: weight = 2.000, loss = 0.00000000

Prediction after training f(5) = 10.000



### using optimizer and loss function

In [61]:
import torch.nn as nn

In [62]:
X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y = torch.tensor([2,4,6,8], dtype=torch.float32)

w = torch.tensor([0.0], requires_grad=True)

In [63]:
def forward(X, w):
    y = X*w 
    return y

In [69]:
loss_func = nn.MSELoss()

In [65]:
optimizer = torch.optim.SGD([w], lr=0.1)

In [70]:
epochs = 100

for i in range(epochs):
    y_pred = forward(X, w)
    loss = loss_func(y_pred, Y)
    loss.backward()
    
    optimizer.step()
    
    optimizer.zero_grad()
    
    if (i%5==0):
        print(f'epoch {i+1}: weight = {w[0]:.3f}, loss = {loss:.8f}')

print(f'\nPrediction after training f(5) = {forward(5, w)[0]:.3f}\n')

epoch 1: weight = 3.000, loss = 30.00000000
epoch 6: weight = 1.969, loss = 0.02929688
epoch 11: weight = 2.001, loss = 0.00002861
epoch 16: weight = 2.000, loss = 0.00000003
epoch 21: weight = 2.000, loss = 0.00000000
epoch 26: weight = 2.000, loss = 0.00000000
epoch 31: weight = 2.000, loss = 0.00000000
epoch 36: weight = 2.000, loss = 0.00000000
epoch 41: weight = 2.000, loss = 0.00000000
epoch 46: weight = 2.000, loss = 0.00000000
epoch 51: weight = 2.000, loss = 0.00000000
epoch 56: weight = 2.000, loss = 0.00000000
epoch 61: weight = 2.000, loss = 0.00000000
epoch 66: weight = 2.000, loss = 0.00000000
epoch 71: weight = 2.000, loss = 0.00000000
epoch 76: weight = 2.000, loss = 0.00000000
epoch 81: weight = 2.000, loss = 0.00000000
epoch 86: weight = 2.000, loss = 0.00000000
epoch 91: weight = 2.000, loss = 0.00000000
epoch 96: weight = 2.000, loss = 0.00000000

Prediction after training f(5) = 10.000



### using pytorch linear model

Pipeline
1. Design model (input size, output size, forward pass)
2. construct loss
3. choose optimizer
4. Training loop
    - forward pass: compute prediction and loss
    - backward pass: compute gradient
    - update weights

In [87]:
X = torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
Y = torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)

n_samples, n_features = X.shape

In [88]:
model = nn.Linear(n_features, n_features)

In [89]:
loss_func = nn.MSELoss()

In [90]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [94]:
epochs = 100

X_test = torch.tensor([5], dtype = torch.float32)

for i in range(epochs):
    y_pred = model(X)
    loss = loss_func(y_pred, Y)
    loss.backward()
    
    optimizer.step()
    
    optimizer.zero_grad()
    
    if (i%5==0):
        w, b = model.parameters()
#         print(f'w {w.item()}')
#         print(f'b {b.item()}')
        print(f'epoch {i+1}: weight = {w.item():.3f}, loss = {loss:.8f}')

print(f'\nPrediction after training f(5) = {model(X_test).item():.3f}\n')

epoch 1: weight = 1.999, loss = 0.00000227
epoch 6: weight = 1.999, loss = 0.00000167
epoch 11: weight = 1.999, loss = 0.00000123
epoch 16: weight = 1.999, loss = 0.00000091
epoch 21: weight = 1.999, loss = 0.00000067
epoch 26: weight = 1.999, loss = 0.00000050
epoch 31: weight = 2.000, loss = 0.00000037
epoch 36: weight = 2.000, loss = 0.00000027
epoch 41: weight = 2.000, loss = 0.00000020
epoch 46: weight = 2.000, loss = 0.00000015
epoch 51: weight = 2.000, loss = 0.00000011
epoch 56: weight = 2.000, loss = 0.00000008
epoch 61: weight = 2.000, loss = 0.00000006
epoch 66: weight = 2.000, loss = 0.00000004
epoch 71: weight = 2.000, loss = 0.00000003
epoch 76: weight = 2.000, loss = 0.00000002
epoch 81: weight = 2.000, loss = 0.00000002
epoch 86: weight = 2.000, loss = 0.00000001
epoch 91: weight = 2.000, loss = 0.00000001
epoch 96: weight = 2.000, loss = 0.00000001

Prediction after training f(5) = 10.000



In [97]:
input1 = torch.randn(1, 4)
weight = torch.randn(2,4)

In [98]:
layer = nn.Linear(in_features=4, out_features=2, bias=False)

In [99]:
layer.weight=nn.Parameter(weight)

In [100]:
weight

tensor([[-2.1447, -0.5679, -0.8758,  1.5979],
        [ 0.4570, -0.1159, -0.1210,  0.3456]])

In [101]:
input1

tensor([[-0.9634, -0.4765,  1.4047, -0.4549]])

In [102]:
layer(input1)

tensor([[ 0.3798, -0.7123]], grad_fn=<MmBackward0>)

In [117]:
np.dot( input1, weight[1].view(-1, 1))

array([[-0.7122795]], dtype=float32)

In [115]:
weight[0].view(-1, 1)

tensor([[-2.1447],
        [-0.5679],
        [-0.8758],
        [ 1.5979]])