## Einsum

In [57]:
A = torch.tensor([[1,2,3],[1,0,1]])   #2*3
B = torch.tensor([[2,1],[1,0],[0,2]]) #3*2

In [58]:
# matrix multiplication
torch.einsum('ij,jk->ik',A,B)

tensor([[4, 7],
        [2, 3]])

In [68]:
# trace
x = torch.eye(3)
torch.einsum('ii->',x)

3.0

In [70]:
# permute
torch.einsum('ij->ji',A)

tensor([[1, 1],
        [2, 0],
        [3, 1]])

In [71]:
# summation
torch.einsum('ij->',A)

tensor(8)

In [72]:
# row sum
torch.einsum('ij->i',A)

tensor([6, 2])

In [73]:
# column sum
torch.einsum('ij->j',A)

tensor([2, 2, 4])

In [75]:
# matrix vector multiplication
v = torch.tensor([[1],[2],[3]])
torch.einsum('ij,jk->ik', A, v)

tensor([[14],
        [ 4]])

In [79]:
# matrix matrix multiplication (2*2)
torch.einsum('ij,kj->ik',A,A)

tensor([[14,  4],
        [ 4,  2]])

In [80]:
# matrix matrix multiplication (3*3)
torch.einsum('ji,jk->ik',A,A)

tensor([[ 2,  2,  4],
        [ 2,  4,  6],
        [ 4,  6, 10]])

In [82]:
A

tensor([[1, 2, 3],
        [1, 0, 1]])

In [83]:
# element wise dot product of A with itself 
torch.einsum('ij,ij->ij', A, A)

tensor([[1, 4, 9],
        [1, 0, 1]])

In [81]:
# element wise dot product of A with itself and summation (Hadamard product)
torch.einsum('ij,ij->', A, A)

tensor(16)

In [96]:
# batch matrix multiplication
x = torch.rand((3,2,5))
y = torch.rand((3,5,3))

In [97]:
torch.einsum('Nij,Njk->Nik',x,y)

tensor([[[1.1965, 0.6622, 1.3722],
         [1.2633, 0.5369, 1.4621]],

        [[1.2327, 1.1342, 1.1992],
         [0.6573, 0.6607, 0.8004]],

        [[0.7744, 0.8805, 0.9745],
         [1.8380, 2.0588, 1.8436]]])

In [106]:
F.softmax(torch.einsum('Nij,Njk->Nik',x,y), dim=2)

tensor([[[0.3599, 0.2110, 0.4291],
         [0.3699, 0.1789, 0.4512]],

        [[0.3480, 0.3154, 0.3366],
         [0.3167, 0.3178, 0.3655]],

        [[0.3000, 0.3336, 0.3665],
         [0.3074, 0.3834, 0.3092]]])

In [103]:
0.3010 + 0.1490 + 0.3355

0.7855

In [94]:
# matrix diagonal
x = torch.rand(3,3)
x

tensor([[0.7104, 0.4975, 0.2797],
        [0.9182, 0.1657, 0.4219],
        [0.7741, 0.9644, 0.4798]])

In [95]:
torch.einsum('ii->i',x)

tensor([0.7104, 0.1657, 0.4798])