In [1]:
import torch
# from torch import nn

In [2]:
tensor = torch.zeros((3, 5))

In [3]:
tensor[0, :] = 1
tensor[1, :] = 2
tensor[2, :] = 3

In [4]:
tensor

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.]])

## view

In [121]:
view = tensor.view(5, 3)

In [122]:
view

tensor([[1., 1., 1.],
        [1., 1., 2.],
        [2., 2., 2.],
        [2., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)

## reshape

In [123]:
reshape = tensor.reshape(5, 3)

In [124]:
reshape

tensor([[1., 1., 1.],
        [1., 1., 2.],
        [2., 2., 2.],
        [2., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)

In [126]:
torch.equal(reshape, view)

True

## transpose

In [128]:
transpose = tensor.transpose(1, 0)

In [129]:
transpose

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]], dtype=torch.float64)

## permute

In [6]:
permute = tensor.permute(1, 0)

In [7]:
permute

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

In [8]:
tensor1 = permute.unsqueeze(0)

In [10]:
tensor1.shape

torch.Size([1, 5, 3])

In [11]:
tensor1.permute(2, 0, 1)

tensor([[[1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3.]]])

In [12]:
tensor1.permute(2, 0, 1).shape

torch.Size([3, 1, 5])

## view vs reshape

In [14]:
a = torch.arange(8).reshape(2, 4)

In [15]:
a

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [ ]:
# [0, 1, 2, 3, 4, 5, 6, 7]

In [22]:
a.stride()

(4, 1)

In [18]:
a.is_contiguous()

True

In [20]:
aT = a.t()
aT

tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])

In [ ]:
# [0, 4, 1, 5, 2, 6, 3, 7]

In [21]:
aT.is_contiguous()

False

In [23]:
aT.stride()

(1, 4)

In [24]:
aT.view(2, 4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [25]:
c = aT.reshape(2, 4)

In [26]:
c

tensor([[0, 4, 1, 5],
        [2, 6, 3, 7]])

In [ ]:
# [0, 1, 2, 3, 4, 5, 6, 7]

In [27]:
c.is_contiguous()

True

In [28]:
c.data_ptr()

94593235502464

In [29]:
aT.data_ptr()

94593233641984

In [30]:
a.data_ptr()

94593233641984

In [ ]:
# [0, 1, 2, 3, 4, 5, 6, 7]

In [31]:
aT.view(2, 2, 2)

tensor([[[0, 4],
         [1, 5]],

        [[2, 6],
         [3, 7]]])

In [32]:
aT.view(2, 2, 2).stride()

(2, 1, 4)

In [33]:
b = aT.reshape(2,2,2)

In [34]:
b.data_ptr()

94593233641984

In [35]:
aT.data_ptr()

94593233641984

to explicitly create a copy of tensor

In [36]:
d = b.clone().detach()

In [37]:
d.data_ptr()

94593233678784